//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EjbAdminServiceServiceSoapBinding", Namespace="http://admin.impl.business.sdi.com/")]
public partial class EjbAdminServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback disableUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback findAllUsersInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback enableUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback findAllUsersOperationCompleted;
    
    private System.Threading.SendOrPostCallback findUserByIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback deepDeleteUserOperationCompleted;
    
    /// <remarks/>
    public EjbAdminServiceService() {
        this.Url = "http://localhost:8280/GTDTaskManagerEJB/AdminService";
    }
    
    /// <remarks/>
    public event disableUserCompletedEventHandler disableUserCompleted;
    
    /// <remarks/>
    public event findAllUsersInfoCompletedEventHandler findAllUsersInfoCompleted;
    
    /// <remarks/>
    public event enableUserCompletedEventHandler enableUserCompleted;
    
    /// <remarks/>
    public event findAllUsersCompletedEventHandler findAllUsersCompleted;
    
    /// <remarks/>
    public event findUserByIdCompletedEventHandler findUserByIdCompleted;
    
    /// <remarks/>
    public event deepDeleteUserCompletedEventHandler deepDeleteUserCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://admin.impl.business.sdi.com/", ResponseNamespace="http://admin.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void disableUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        this.Invoke("disableUser", new object[] {
                    arg0,
                    arg0Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindisableUser(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("disableUser", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EnddisableUser(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void disableUserAsync(long arg0, bool arg0Specified) {
        this.disableUserAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void disableUserAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.disableUserOperationCompleted == null)) {
            this.disableUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OndisableUserOperationCompleted);
        }
        this.InvokeAsync("disableUser", new object[] {
                    arg0,
                    arg0Specified}, this.disableUserOperationCompleted, userState);
    }
    
    private void OndisableUserOperationCompleted(object arg) {
        if ((this.disableUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.disableUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://admin.impl.business.sdi.com/", ResponseNamespace="http://admin.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public userInfo[] findAllUsersInfo() {
        object[] results = this.Invoke("findAllUsersInfo", new object[0]);
        return ((userInfo[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindAllUsersInfo(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findAllUsersInfo", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public userInfo[] EndfindAllUsersInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((userInfo[])(results[0]));
    }
    
    /// <remarks/>
    public void findAllUsersInfoAsync() {
        this.findAllUsersInfoAsync(null);
    }
    
    /// <remarks/>
    public void findAllUsersInfoAsync(object userState) {
        if ((this.findAllUsersInfoOperationCompleted == null)) {
            this.findAllUsersInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAllUsersInfoOperationCompleted);
        }
        this.InvokeAsync("findAllUsersInfo", new object[0], this.findAllUsersInfoOperationCompleted, userState);
    }
    
    private void OnfindAllUsersInfoOperationCompleted(object arg) {
        if ((this.findAllUsersInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findAllUsersInfoCompleted(this, new findAllUsersInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://admin.impl.business.sdi.com/", ResponseNamespace="http://admin.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void enableUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        this.Invoke("enableUser", new object[] {
                    arg0,
                    arg0Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginenableUser(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("enableUser", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndenableUser(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void enableUserAsync(long arg0, bool arg0Specified) {
        this.enableUserAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void enableUserAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.enableUserOperationCompleted == null)) {
            this.enableUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenableUserOperationCompleted);
        }
        this.InvokeAsync("enableUser", new object[] {
                    arg0,
                    arg0Specified}, this.enableUserOperationCompleted, userState);
    }
    
    private void OnenableUserOperationCompleted(object arg) {
        if ((this.enableUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.enableUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://admin.impl.business.sdi.com/", ResponseNamespace="http://admin.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user[] findAllUsers() {
        object[] results = this.Invoke("findAllUsers", new object[0]);
        return ((user[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindAllUsers(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findAllUsers", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public user[] EndfindAllUsers(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((user[])(results[0]));
    }
    
    /// <remarks/>
    public void findAllUsersAsync() {
        this.findAllUsersAsync(null);
    }
    
    /// <remarks/>
    public void findAllUsersAsync(object userState) {
        if ((this.findAllUsersOperationCompleted == null)) {
            this.findAllUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAllUsersOperationCompleted);
        }
        this.InvokeAsync("findAllUsers", new object[0], this.findAllUsersOperationCompleted, userState);
    }
    
    private void OnfindAllUsersOperationCompleted(object arg) {
        if ((this.findAllUsersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findAllUsersCompleted(this, new findAllUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://admin.impl.business.sdi.com/", ResponseNamespace="http://admin.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user findUserById([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("findUserById", new object[] {
                    arg0,
                    arg0Specified});
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindUserById(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findUserById", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public user EndfindUserById(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public void findUserByIdAsync(long arg0, bool arg0Specified) {
        this.findUserByIdAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void findUserByIdAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.findUserByIdOperationCompleted == null)) {
            this.findUserByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindUserByIdOperationCompleted);
        }
        this.InvokeAsync("findUserById", new object[] {
                    arg0,
                    arg0Specified}, this.findUserByIdOperationCompleted, userState);
    }
    
    private void OnfindUserByIdOperationCompleted(object arg) {
        if ((this.findUserByIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findUserByIdCompleted(this, new findUserByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://admin.impl.business.sdi.com/", ResponseNamespace="http://admin.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void deepDeleteUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        this.Invoke("deepDeleteUser", new object[] {
                    arg0,
                    arg0Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindeepDeleteUser(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("deepDeleteUser", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EnddeepDeleteUser(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void deepDeleteUserAsync(long arg0, bool arg0Specified) {
        this.deepDeleteUserAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void deepDeleteUserAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.deepDeleteUserOperationCompleted == null)) {
            this.deepDeleteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeepDeleteUserOperationCompleted);
        }
        this.InvokeAsync("deepDeleteUser", new object[] {
                    arg0,
                    arg0Specified}, this.deepDeleteUserOperationCompleted, userState);
    }
    
    private void OndeepDeleteUserOperationCompleted(object arg) {
        if ((this.deepDeleteUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.deepDeleteUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://admin.impl.business.sdi.com/")]
public partial class userInfo {
    
    private int numTareasCompletadasField;
    
    private int numTareasCompletadasRetrasadasField;
    
    private int numTareasNoPlanificadasField;
    
    private int numTareasPlanificadasField;
    
    private user userField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int numTareasCompletadas {
        get {
            return this.numTareasCompletadasField;
        }
        set {
            this.numTareasCompletadasField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int numTareasCompletadasRetrasadas {
        get {
            return this.numTareasCompletadasRetrasadasField;
        }
        set {
            this.numTareasCompletadasRetrasadasField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int numTareasNoPlanificadas {
        get {
            return this.numTareasNoPlanificadasField;
        }
        set {
            this.numTareasNoPlanificadasField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int numTareasPlanificadas {
        get {
            return this.numTareasPlanificadasField;
        }
        set {
            this.numTareasPlanificadasField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://admin.impl.business.sdi.com/")]
public partial class user {
    
    private string emailField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private bool isAdminField;
    
    private bool isAdminFieldSpecified;
    
    private string loginField;
    
    private string passwordField;
    
    private userStatus statusField;
    
    private bool statusFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool isAdmin {
        get {
            return this.isAdminField;
        }
        set {
            this.isAdminField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isAdminSpecified {
        get {
            return this.isAdminFieldSpecified;
        }
        set {
            this.isAdminFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public userStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://admin.impl.business.sdi.com/")]
public enum userStatus {
    
    /// <comentarios/>
    ENABLED,
    
    /// <comentarios/>
    DISABLED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void disableUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findAllUsersInfoCompletedEventHandler(object sender, findAllUsersInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findAllUsersInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findAllUsersInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public userInfo[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((userInfo[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void enableUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findAllUsersCompletedEventHandler(object sender, findAllUsersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findAllUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findAllUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public user[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((user[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findUserByIdCompletedEventHandler(object sender, findUserByIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findUserByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findUserByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public user Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((user)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void deepDeleteUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
