package com.sdi.ws.admin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2017-04-27T10:33:33.563+02:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://admin.impl.business.sdi.com/", name = "AdminService")
@XmlSeeAlso({ObjectFactory.class})
public interface AdminService {

    @RequestWrapper(localName = "disableUser", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.DisableUser")
    @WebMethod
    @ResponseWrapper(localName = "disableUserResponse", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.DisableUserResponse")
    public void disableUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    ) throws BusinessException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllUsersInfo", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.FindAllUsersInfo")
    @WebMethod
    @ResponseWrapper(localName = "findAllUsersInfoResponse", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.FindAllUsersInfoResponse")
    public java.util.List<com.sdi.ws.admin.UserInfo> findAllUsersInfo() throws BusinessException_Exception;

    @RequestWrapper(localName = "enableUser", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.EnableUser")
    @WebMethod
    @ResponseWrapper(localName = "enableUserResponse", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.EnableUserResponse")
    public void enableUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    ) throws BusinessException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllUsers", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.FindAllUsers")
    @WebMethod
    @ResponseWrapper(localName = "findAllUsersResponse", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.FindAllUsersResponse")
    public java.util.List<com.sdi.ws.admin.User> findAllUsers() throws BusinessException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findUserById", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.FindUserById")
    @WebMethod
    @ResponseWrapper(localName = "findUserByIdResponse", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.FindUserByIdResponse")
    public com.sdi.ws.admin.User findUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    ) throws BusinessException_Exception;

    @RequestWrapper(localName = "deepDeleteUser", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.DeepDeleteUser")
    @WebMethod
    @ResponseWrapper(localName = "deepDeleteUserResponse", targetNamespace = "http://admin.impl.business.sdi.com/", className = "com.sdi.ws.admin.DeepDeleteUserResponse")
    public void deepDeleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    ) throws BusinessException_Exception;
}
