
package com.sdi.ws.admin;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2017-04-27T10:33:33.532+02:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "BusinessException", targetNamespace = "http://admin.impl.business.sdi.com/")
public class BusinessException_Exception extends Exception {
    
    private com.sdi.ws.admin.BusinessException businessException;

    public BusinessException_Exception() {
        super();
    }
    
    public BusinessException_Exception(String message) {
        super(message);
    }
    
    public BusinessException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public BusinessException_Exception(String message, com.sdi.ws.admin.BusinessException businessException) {
        super(message);
        this.businessException = businessException;
    }

    public BusinessException_Exception(String message, com.sdi.ws.admin.BusinessException businessException, Throwable cause) {
        super(message, cause);
        this.businessException = businessException;
    }

    public com.sdi.ws.admin.BusinessException getFaultInfo() {
        return this.businessException;
    }
}
