package com.sdi.ws.admin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2017-04-27T10:33:33.579+02:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "EjbAdminServiceService", 
                  wsdlLocation = "http://localhost:8280/GTDTaskManagerEJB/AdminService?wsdl",
                  targetNamespace = "http://admin.impl.business.sdi.com/") 
public class EjbAdminServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://admin.impl.business.sdi.com/", "EjbAdminServiceService");
    public final static QName AdminServicePort = new QName("http://admin.impl.business.sdi.com/", "AdminServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8280/GTDTaskManagerEJB/AdminService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EjbAdminServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8280/GTDTaskManagerEJB/AdminService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EjbAdminServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EjbAdminServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EjbAdminServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EjbAdminServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EjbAdminServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EjbAdminServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AdminService
     */
    @WebEndpoint(name = "AdminServicePort")
    public AdminService getAdminServicePort() {
        return super.getPort(AdminServicePort, AdminService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminService
     */
    @WebEndpoint(name = "AdminServicePort")
    public AdminService getAdminServicePort(WebServiceFeature... features) {
        return super.getPort(AdminServicePort, AdminService.class, features);
    }

}
